### ISSUE TITLE
Publish this package in a CRAN style repository

### ISSUE THREAD

**Issue by lmullen** [ropensci/genderdata#5]
Will this package go on CRAN? Unlikely. Will rOpenSci support a CRAN style repository or do I need to roll my own?

**Comment by sckott** [comment]
we have http://www.carlboettiger.info/drat/ https://github.com/cboettig/drat - just need to get carl to add this pkg I think - actually looks like this pkg is already in there https://github.com/cboettig/drat/tree/gh-pages/src/contrib

**Comment by cboettig** [comment]
our drat will automatically pull anything on the ropensci GitHub flagged as both "installable" and "good" by @sckott 's `ropkgs` package (at least it should, I still have to resolve some issues about how we handle packages like redisAPI where we can't build the vignette on the fly; guess we'd need a tag from `ropkgs` to know that.)  

Currently have to resolve some issue in which aws push fails at random, but the github-based endpoint should be working.  We need to get all of those endpoints migrated over to ropensci addresses anyhow.

**Comment by lmullen** [comment]
Thanks, @sckott and @cboettig. I didn't even expect you to be watching this issue.

I have the same basic problem with the gender and the USAboundaries packages. Both need large (> 5Mb) datasets to do their work, so I have put the code in the main package and the data in separate data-only packages. This also helps immensely with updates. I have a new release of USAboundaries that is about ready to go to CRAN (see issue referenced above) and I'd like to depend on the data package(s) by putting them in the rOpenSci drat repo. Some questions for you, then:
1. What exactly do I need to do to get packages in the drat repo? Send a PR to ropkgs? 
2. Is the `http://www.carlboettiger.info/drat/` endpoint the best one to use, or are we about to get one with an rOpenSci url?
3. Since both gender and USAboundaries are already published packages, I assume I can do this without going through onboarding. (This is more of a comment than a question ... :-)

**Comment by cboettig** [comment]
@lmullen We might want to explore a model of hosting the data in an external repo (zenodo, maybe just github) rather than a data package.  It could have the added benefit of making the data a bit more cross-platform.  Do you think that would be workable in this context?

Re drat, it's still pretty new; things aren't quite finished.  but to answer your questions:
1. @sckott How does ropkgs data get updated? you do this manually or do you have a script?  @lmullen from your end, the idea should be that once it's onboarded to the `ropensci` GitHub account, that version should be automatically added to drat and updated nightly.  
2.  `http://carlboettiger.info/drat` is really just a testing version, the idea is to use `http://packages.ropensci.org` I think.  
3.  Right; since they are on github.com/ropensci, they're automatically in drat as well.  The idea here is that drat will have the most recent (nightly) version from github, rather than the stable version from cran.  A user could thus install or update any ropensci packages they already had installed to the latest GitHub version by using `install.packages()` and `update.packages()` base R functions.  

On our end, when `drat` is finished this will also mean we get download statistics for the drat-based installs.

**Comment by lmullen** [comment]
@cboettig I'll consider Zenodo for the future, but in this case all the package code already assumes that we're dealing with data in an R package, and I think that helps performance (with LazyLoad) and keeping versions in sync. I think the rOpenSci drat repository will be idea for these packages.

What is your rough timeline for making the `packages.ropensci.org` version of the repository? Just wondering whether I should wait to release new versions of the packages.

**Comment by sckott** [comment]
> How does ropkgs data get updated? you do this manually or do you have a script?

I manually update this json file https://github.com/ropensci/roregistry/blob/master/registry.json - but https://github.com/ropensci/roapi will replace that, so very little will be manual - I'll keep the json file at ropensci/roregistry up to date until the API is out

**Comment by cboettig** [comment]
@sckott Nice!  How will roapi handle the annotations (e.g. `good`, `installable`)?  (Maybe this question belongs in a different thread... sorry @lmullen )

**Comment by sckott** [comment]
@cboettig  see https://github.com/ropensci/roapi/issues/1
